feature(kb): add SD of components od user interface
semsystems/semantic-ui pull request #5
Opened 2021-04-08 10:53 UTC by KsenBantsevich

2021-04-20 18:21 UTC, irinagrigorjewa requested changes

2021-04-20 18:21 UTC, irinagrigorjewa commented on kb/section_subject_domain_of_interface_components/concepts/concept_coordinate_y.scs
> +=> nrel_json_idtf:[concept coordinate y];
Изменить на => nrel_json_idtf:[y];

2021-04-20 18:21 UTC, irinagrigorjewa commented on kb/section_subject_domain_of_interface_components/concepts/concept_coordinate_x.scs
> +=> nrel_json_idtf:[concept coordinate x];
Изменить на => nrel_json_idtf:[x];

2021-04-20 18:21 UTC, irinagrigorjewa commented on kb/section_subject_domain_of_interface_components/relations/nrel_pt.scs
> +<-antitransitive_relation;
Добавить => nrel_json_idtf:[pt]

2021-04-20 18:21 UTC, irinagrigorjewa commented on kb/section_subject_domain_of_interface_components/relations/nrel_dp.scs
> +<-antitransitive_relation;
Добавить => nrel_json_idtf:[dp]

2021-04-20 18:21 UTC, irinagrigorjewa commented on kb/section_subject_domain_of_interface_components/concepts/concept_text_size.scs
> +=> nrel_json_idtf:[text size];
=> nrel_json_idtf:[textSize];

2021-04-26 11:27 UTC, irinagrigorjewa requested changes

2021-04-26 11:27 UTC, irinagrigorjewa commented on kb/section_subject_domain_of_interface_components/concepts/concept_alt.scs
> +		-> rrel_example:
Убрать немецкий во всех файлах

2021-07-06 16:11 UTC, irinagrigorjewa requested changes

2021-07-06 16:11 UTC, irinagrigorjewa commented on kb/section_subject_domain_of_interface_components/concepts/concept_text_color.scs
> +=> nrel_json_idtf:[text color];
=> nrel_json_idtf:[textColor];

2021-07-21 12:55 UTC, irinagrigorjewa requested changes

2021-07-21 12:55 UTC, irinagrigorjewa commented on kb/section_subject_domain_of_interface_components/concepts/concept_alt.scs
> +	(* <- lang_ru;; *);
Добавить картинки ко всем компонентам

2021-07-21 12:55 UTC, irinagrigorjewa commented on kb/section_subject_domain_of_interface_components/concepts/concept_disable.scs
> +	[доступ и изменение заблокирован]
[доступ и изменение разрешен]

2021-07-21 12:55 UTC, irinagrigorjewa commented on kb/section_subject_domain_of_interface_components/concepts/concept_disable.scs
> +	[доступ и изменение разрешен]
[доступ и изменение заблокирован]

2021-07-21 12:55 UTC, irinagrigorjewa commented on kb/section_subject_domain_of_interface_components/concepts/concept_disable.scs
> +concept_disable_true
<- sc_node_class;

2021-07-21 12:55 UTC, irinagrigorjewa commented on kb/section_subject_domain_of_interface_components/concepts/concept_disable.scs
> +concept_disable_false
<- sc_node_class;

2021-07-21 12:55 UTC, irinagrigorjewa commented on kb/section_subject_domain_of_interface_components/concepts/concept_checked.scs
> +concept_checked_false
<- sc_node_class;

2021-07-21 12:55 UTC, irinagrigorjewa commented on kb/section_subject_domain_of_interface_components/concepts/concept_checked.scs
> +concept_checked_true
<- sc_node_class;

2021-08-03 11:14 UTC, irinagrigorjewa requested changes

2021-08-03 11:14 UTC, irinagrigorjewa commented on kb/section_subject_domain_of_interface_components/concepts/concept_checked.scs
> +<- concept_disable;
```suggestion
<- concept_checked;
```

2021-08-03 11:14 UTC, irinagrigorjewa commented on kb/section_subject_domain_of_interface_components/concepts/concept_checked.scs
> +<- concept_disable;
```suggestion
<- concept_checked;
```

2021-08-03 12:55 UTC, irinagrigorjewa requested changes

2021-08-03 12:55 UTC, irinagrigorjewa commented on kb/section_subject_domain_of_interface_components/examples/radioButton2.scs
> +@pair18= (concept_checked_false -> radioButton2);;
```suggestion
@pair19= (concept_checked_false -> radioButton2);;
```

2021-08-03 12:55 UTC, irinagrigorjewa commented on kb/section_subject_domain_of_interface_components/examples/radioButton1.scs
> +@pair18= (concept_checked_true -> radioButton1);;
```suggestion
@pair19= (concept_checked_true -> radioButton1);;
```

2021-08-04 14:03 UTC, irinagrigorjewa requested changes

2021-08-04 14:03 UTC, irinagrigorjewa commented on kb/section_subject_domain_of_interface_components/examples/textField2.scs
> +@pair58 = (..node14=> @link4);;
```suggestion
@pair58 = (..node14=> @link6);;
```

2021-08-04 14:03 UTC, irinagrigorjewa commented on kb/section_subject_domain_of_interface_components/examples/textField2.scs
> +@pair58 = (..node14-> textField2);;
```suggestion
@pair60 = (..node14-> textField2);;
```

2021-08-04 14:03 UTC, irinagrigorjewa commented on kb/section_subject_domain_of_interface_components/examples/textField2.scs
> +@pair59 = (concept_disable_false -> textField2);;
```suggestion
@pair61 = (concept_disable_false -> textField2);;
```

2021-08-04 14:03 UTC, irinagrigorjewa commented on kb/section_subject_domain_of_interface_components/examples/label1.scs
> +@pair52 = (concept_coordinate_y -> ..node6);;
```suggestion
@pair52 = (concept_coordinate_y -> ..node11);;
```

2021-08-04 14:03 UTC, irinagrigorjewa commented on kb/section_subject_domain_of_interface_components/examples/label1.scs
> +@pair31 = (..node11-> label1);;
```suggestion
@pair31 = (..node6-> label1);;
```

2021-08-04 14:03 UTC, irinagrigorjewa commented on kb/section_subject_domain_of_interface_components/examples/label1.scs
> +@pair28 = (..node11=> @link5);;
```suggestion
@pair28 = (..node6=> @link5);;
```

2021-08-11 13:21 UTC, MikhailSadovsky commented
Closed as new #8 opened with same logic

2021-08-11 13:21 UTC, closed without merging